/**
 * generateArithmeticQuestions.js
 *
 * Generates all arithmetic questions for the banana-math question bank
 * and writes them to scripts/arithmetic_questions.json.
 *
 * Then run: node scripts/addQuestionsToDB.js scripts/arithmetic_questions.json
 *
 * Usage:
 *   node scripts/generateArithmeticQuestions.js
 *   node scripts/generateArithmeticQuestions.js --range 50   (use -50 to 50)
 *   node scripts/generateArithmeticQuestions.js --mul-range 12  (times tables up to 12)
 *   node scripts/generateArithmeticQuestions.js --dry-run    (count only, no file write)
 *
 * Rules:
 *   Addition/Subtraction : operand_a and operand_b from [-range, range]
 *   Multiplication       : operand_a and operand_b from [-mul_range, mul_range]
 *   Division             : integer-only (no remainders), divisor != 0
 *                          generated by reversing multiplication: (a*b) ÷ b = a
 */

const fs = require("fs")
const path = require("path")

// ─── Config ──────────────────────────────────────────────────────────────────

const args = process.argv.slice(2)
const getArg = (flag, defaultVal) => {
  const idx = args.indexOf(flag)
  if (idx !== -1 && args[idx + 1] !== undefined) return parseInt(args[idx + 1], 10)
  return defaultVal
}

const ADD_SUB_RANGE = getArg("--range", 99) // operands from -99 to 99
const MUL_DIV_RANGE = getArg("--mul-range", 12) // times tables up to 12
const DRY_RUN = args.includes("--dry-run")
const OUT_FILE = path.resolve(process.cwd(), "scripts/arithmetic_questions.json")

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getDigitCount(n) {
  if (n === 0) return 1
  return Math.floor(Math.log10(Math.abs(n))) + 1
}

function calcDifficulty(a, b, answer) {
  let d = getDigitCount(a) + getDigitCount(b) + getDigitCount(answer)
  if (a < 0 || b < 0 || answer < 0) d += 3
  return d
}

function hasNeg(a, b, answer) {
  return a < 0 || b < 0 || answer < 0
}

// ─── Generators ──────────────────────────────────────────────────────────────

function generateAddition(range) {
  const questions = []
  for (let a = -range; a <= range; a++) {
    for (let b = -range; b <= range; b++) {
      const answer = a + b
      questions.push({
        category: "arithmetic",
        sub_type: "addition",
        operand_a: a,
        operand_b: b,
        operator: "+",
        question_text: `${a} + ${b} = ?`,
        correct_answer: String(answer),
        has_negatives: hasNeg(a, b, answer),
        difficulty: calcDifficulty(a, b, answer)
      })
    }
  }
  return questions
}

function generateSubtraction(range) {
  const questions = []
  for (let a = -range; a <= range; a++) {
    for (let b = -range; b <= range; b++) {
      const answer = a - b
      questions.push({
        category: "arithmetic",
        sub_type: "subtraction",
        operand_a: a,
        operand_b: b,
        operator: "-",
        question_text: `${a} - ${b} = ?`,
        correct_answer: String(answer),
        has_negatives: hasNeg(a, b, answer),
        difficulty: calcDifficulty(a, b, answer)
      })
    }
  }
  return questions
}

function generateMultiplication(range) {
  const questions = []
  for (let a = -range; a <= range; a++) {
    for (let b = -range; b <= range; b++) {
      const answer = a * b
      questions.push({
        category: "arithmetic",
        sub_type: "multiplication",
        operand_a: a,
        operand_b: b,
        operator: "*",
        question_text: `${a} × ${b} = ?`,
        correct_answer: String(answer),
        has_negatives: hasNeg(a, b, answer),
        difficulty: calcDifficulty(a, b, answer)
      })
    }
  }
  return questions
}

function generateDivision(range) {
  // Build from multiplication table to guarantee integer-only results.
  // For each (a, b), the question is (a*b) ÷ b = a (when b != 0).
  // Skip 0 ÷ 0 and use a Set to deduplicate (same dividend/divisor pair).
  const seen = new Set()
  const questions = []

  for (let a = -range; a <= range; a++) {
    for (let b = -range; b <= range; b++) {
      if (b === 0) continue

      const dividend = a * b // operand_a in the question
      const divisor = b // operand_b in the question
      const answer = a

      const key = `${dividend}/${divisor}`
      if (seen.has(key)) continue
      seen.add(key)

      questions.push({
        category: "arithmetic",
        sub_type: "division",
        operand_a: dividend,
        operand_b: divisor,
        operator: "/",
        question_text: `${dividend} ÷ ${divisor} = ?`,
        correct_answer: String(answer),
        has_negatives: hasNeg(dividend, divisor, answer),
        difficulty: calcDifficulty(dividend, divisor, answer)
      })
    }
  }
  return questions
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function generate() {
  console.log("\n🍌 banana-math Question Generator")
  console.log(`   Add/Sub range  : -${ADD_SUB_RANGE} to ${ADD_SUB_RANGE}`)
  console.log(`   Mul/Div range  : -${MUL_DIV_RANGE} to ${MUL_DIV_RANGE}`)
  console.log(`   Dry run        : ${DRY_RUN}`)
  console.log()

  console.log("Generating addition...")
  const add = generateAddition(ADD_SUB_RANGE)
  console.log(`  → ${add.length} questions`)

  console.log("Generating subtraction...")
  const sub = generateSubtraction(ADD_SUB_RANGE)
  console.log(`  → ${sub.length} questions`)

  console.log("Generating multiplication...")
  const mul = generateMultiplication(MUL_DIV_RANGE)
  console.log(`  → ${mul.length} questions`)

  console.log("Generating division (integer-only)...")
  const div = generateDivision(MUL_DIV_RANGE)
  console.log(`  → ${div.length} questions`)

  const all = [...add, ...sub, ...mul, ...div]
  console.log(`\n  Total: ${all.length.toLocaleString()} questions`)

  if (DRY_RUN) {
    console.log("\n  Dry run — no file written.\n")
    return
  }

  fs.writeFileSync(OUT_FILE, JSON.stringify(all, null, 2))
  console.log(`\n✅ Written to ${OUT_FILE}`)
  console.log(`   Next: node scripts/addQuestionsToDB.js scripts/arithmetic_questions.json\n`)
}

generate()
