# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - "*-*"
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!master" # excludes master
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - $default_branch
      - master
      - matrix
    types:
      - closed
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    strategy:
      matrix:
        node-version: [22.3.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    outputs:
      node_version: ${{ steps.set_output.outputs.node_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
      - name: Set Node.js version output
        id: set_output
        run: echo "::set-output name=node_version::${{ matrix.node-version }}"
        
  security:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --severity-threshold=critical
  build_push_docker:
    needs: [security]
    name: build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            bhrugur1/banana-math
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha 
            type=ref,event=tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5

        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  deploy_to_gcp:
    needs: [build_push_docker]
    if: github.ref == 'refs/heads/deployment'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PROJECT_ID: banana-math
      IMAGE_NAME: bhrugur1/banana-math
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@deployment
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
        # gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

      # - uses: actions/checkout@v2
      #   with:
      #     submodules: 'true'

      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ needs.build.outputs.node_version }}

      # - name: Install dependencies
      #   run: npm ci # or 'npm install' if you prefer

      # - name: Build the Next.js project
      #   run: npm run build
      #   env:
      #     MONGODB_URI: ${{ secrets.MONGODB_URI }} # Set the MONGODB_URI environment variable

      # - name: Publish to Cloudflare Pages
      #   uses: cloudflare/pages-action@v1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: banana-math
      #     directory: .next
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      #     branch: deployment
      #     wranglerVersion: '3'